// This file is generated and will be overwritten automatically.

#import "MBNNLaneChangeDirection_Internal.h"
#import "MBNNLaneChangeState_Internal.h"
#import "MBNNTrafficSignType_Internal.h"
#import "MBNNDetectedObjectCategory_Internal.h"
#import "MBNNFeatureColor_Internal.h"
#import "MBNNLaneMarkingType_Internal.h"
#import "MBNNRoadMarkingType_Internal.h"
#import "MBNNRoadEdgeType_Internal.h"
#import "MBNNLaneChangeAssistData_Internal.h"
#import "MBNNLocalizedLaneData_Internal.h"
#import "MBNNDetectionState_Internal.h"
#import "MBNNDetectedObject_Internal.h"
#import "MBNNDetectedObjects_Internal.h"
#import "MBNNPerceptionFeatureData_Internal.h"
#import "MBNNPerceptionLaneMarkingFeature_Internal.h"
#import "MBNNPerceptionRoadEdgeFeature_Internal.h"
#import "MBNNPerceptionRoadMarkingFeature_Internal.h"
#import "MBNNPerceptionTrafficSignFeature_Internal.h"
#import "MBNNPerceptionData_Internal.h"
#import "MBNNPerceptionFeature_Internal.h"
