// This file is generated and will be overwritten automatically.

#import "MBNNStandard_Internal.h"
#import "MBNNOpenLRFunctionalRoadClass_Internal.h"
#import "MBNNOrientation_Internal.h"
#import "MBNNSideOfRoad_Internal.h"
#import "MBNNOpenLR_Internal.h"
#import "MBNNLocationReferencePoint_Internal.h"
#import "MBNNLineLocationReference_Internal.h"
#import "MBNNPointAlongLineLocationReference_Internal.h"
#import "MBNNPOIWithAccessPointLocationReference_Internal.h"
#import "MBNNCircleLocationReference_Internal.h"
#import "MBNNRectangleLocationReference_Internal.h"
#import "MBNNGridLocationReference_Internal.h"
#import "MBNNPolygonLocationReference_Internal.h"
#import "MBNNLineAttributes_Internal.h"
#import "MBNNClosedLineLocationReference_Internal.h"
#import "MBNNGeoCoordinateLocationReference_Internal.h"
#import "MBNNDecodingError_Internal.h"
#import "MBNNOpenLRDecoder_Internal.h"
#import "MBNNLocationReference_Internal.h"
