// This file is generated and will be overwritten automatically.

#import "MBNNElectronicHorizonResultType_Internal.h"
#import "MBNNElectronicHorizonEdge_Internal.h"
#import "MBNNElectronicHorizon_Internal.h"
#import "MBNNGate_Internal.h"
#import "MBNNPointDistanceInfo_Internal.h"
#import "MBNNGantryDistanceInfo_Internal.h"
#import "MBNNPolygonDistanceInfo_Internal.h"
#import "MBNNSubGraphDistanceInfo_Internal.h"
#import "MBNNLineDistanceInfo_Internal.h"
#import "MBNNRoadObjectDistance_Internal.h"
#import "MBNNRoadObjectEnterExitInfo_Internal.h"
#import "MBNNRoadObjectPassInfo_Internal.h"
#import "MBNNAlertsServiceOptions_Internal.h"
#import "MBNNElectronicHorizonOptions_Internal.h"
#import "MBNNElectronicHorizon360Edge_Internal.h"
#import "MBNNElectronicHorizon360Graph_Internal.h"
#import "MBNNElectronicHorizonPosition_Internal.h"
#import "MBNNElectronicHorizonObserver_Internal.h"
#import "MBNNGenerateEh360Callback_Internal.h"
#import "MBNNRoadObjectDistanceInfo_Internal.h"
