// This file is generated and will be overwritten automatically.

#import <Foundation/Foundation.h>

/**
 * WARNING: This API is not intended for public usage. It can be deleted or changed without any notice.
 * The type of the road item.
 * Contains traffic signs and other not-sign road items.
 */
// NOLINTNEXTLINE(modernize-use-using)
typedef NS_ENUM(NSInteger, MBNNRoadItemType)
{
    MBNNRoadItemTypeDangerSign,
    MBNNRoadItemTypePassLeftOrRightSideSign,
    MBNNRoadItemTypePassLeftSideSign,
    MBNNRoadItemTypePassRightSideSign,
    MBNNRoadItemTypeDomesticAnimalsCrossingSign,
    MBNNRoadItemTypeWildAnimalsCrossingSign,
    MBNNRoadItemTypeRoadWorksSign,
    MBNNRoadItemTypeResidentialAreaSign,
    MBNNRoadItemTypeEndOfResidentialAreaSign,
    MBNNRoadItemTypeRightBendSign,
    MBNNRoadItemTypeLeftBendSign,
    MBNNRoadItemTypeDoubleBendRightFirstSign,
    MBNNRoadItemTypeDoubleBendLeftFirstSign,
    MBNNRoadItemTypeCurvyRoadSign,
    MBNNRoadItemTypeOvertakingByGoodsVehiclesProhibitedSign,
    MBNNRoadItemTypeEndOfProhibitionOnOvertakingForGoodsVehiclesSign,
    MBNNRoadItemTypeDangerousIntersectionSign,
    MBNNRoadItemTypeTunnelSign,
    MBNNRoadItemTypeFerryTerminalSign,
    MBNNRoadItemTypeNarrowBridgeSign,
    MBNNRoadItemTypeHumpbackBridgeBridgeSign,
    MBNNRoadItemTypeRiverBankSign,
    MBNNRoadItemTypeRiverBankLeftSign,
    MBNNRoadItemTypeYieldSign,
    MBNNRoadItemTypeStopSign,
    MBNNRoadItemTypePriorityRoadSign,
    MBNNRoadItemTypeIntersectionSign,
    MBNNRoadItemTypeIntersectionWithMinorRoadSign,
    MBNNRoadItemTypeIntersectionWithPriorityToTheRightSign,
    MBNNRoadItemTypeDirectionToTheRightSign,
    MBNNRoadItemTypeDirectionToTheLeftSign,
    MBNNRoadItemTypeCarriagewayNarrowsSign,
    MBNNRoadItemTypeCarriagewayNarrowsRightSign,
    MBNNRoadItemTypeCarriagewayNarrowsLeftSign,
    MBNNRoadItemTypeLaneMergeLeftSign,
    MBNNRoadItemTypeLaneMergeRightSign,
    MBNNRoadItemTypeLaneMergeCenterSign,
    MBNNRoadItemTypeOvertakingProhibitedSign,
    MBNNRoadItemTypeEndOfProhibitionOnOvertakingSign,
    MBNNRoadItemTypeProtectiveOvertakingSign,
    MBNNRoadItemTypePedestriansSign,
    MBNNRoadItemTypePedestrianCrossingSign,
    MBNNRoadItemTypeChildrenSign,
    MBNNRoadItemTypeSchoolZoneSign,
    MBNNRoadItemTypeCyclistsSign,
    MBNNRoadItemTypeTwoWayTrafficSign,
    MBNNRoadItemTypeRailwayCrossingWithGatesSign,
    MBNNRoadItemTypeRailwayCrossingWithoutGatesSign,
    MBNNRoadItemTypeRailwayCrossingSign,
    MBNNRoadItemTypeTramwaySign,
    MBNNRoadItemTypeFallingRocksSign,
    MBNNRoadItemTypeFallingRocksLeftSign,
    MBNNRoadItemTypeFallingRocksRightSign,
    MBNNRoadItemTypeSteepDropLeftSign,
    MBNNRoadItemTypeSteepDropRightSign,
    MBNNRoadItemTypeVariableSignMechanicElementsSign,
    MBNNRoadItemTypeSlipperyRoadSign,
    MBNNRoadItemTypeSteepAscentSign,
    MBNNRoadItemTypeSteepDescentSign,
    MBNNRoadItemTypeUnevenRoadSign,
    MBNNRoadItemTypeHumpSign,
    MBNNRoadItemTypeDipSign,
    MBNNRoadItemTypeRoadFloodsSign,
    MBNNRoadItemTypeIcyRoadSign,
    MBNNRoadItemTypeSideWindsSign,
    MBNNRoadItemTypeTrafficCongestionSign,
    MBNNRoadItemTypeHighAccidentAreaSign,
    MBNNRoadItemTypeVariableSignLightElementsSign,
    MBNNRoadItemTypePriorityOverOncomingTrafficSign,
    MBNNRoadItemTypePriorityForOncomingTrafficSign,
    MBNNRoadItemTypeSpeedLimitSign,
    MBNNRoadItemTypeTollBooth,
    MBNNRoadItemTypeRoadCamSpeedIntervalEnd,
    MBNNRoadItemTypeRoadCamSpeedIntervalStart,
    MBNNRoadItemTypeRoadCamSpeedInterval,
    MBNNRoadItemTypeRoadCamLaneNonMotorized,
    MBNNRoadItemTypeRoadCamLaneEmergency,
    MBNNRoadItemTypeRoadCamLaneBus,
    MBNNRoadItemTypeRoadCamViolation,
    MBNNRoadItemTypeRoadCamRedLight,
    MBNNRoadItemTypeRoadCamSurveillance,
    MBNNRoadItemTypeRoadCamSpeedCurrentSpeed,
    MBNNRoadItemTypeRailroadCrossing,
    MBNNRoadItemTypeZebra,
    MBNNRoadItemTypeSpeedBump,
    MBNNRoadItemTypeTrafficLight
} NS_SWIFT_NAME(RoadItemType);

NSString* MBNNRoadItemTypeToString(MBNNRoadItemType road_item_type);
