// This file is generated and will be overwritten automatically.

#import "MBNNMessageBinaryFormat.h"
#import "MBNNAdasisConfigDataSending.h"
#import "MBNNAdasisConfigMessageOptions.h"
#import "MBNNAdasisConfigProfileshortTypeOptions.h"
#import "MBNNAdasisConfigProfilelongTrafficEventIds.h"
#import "MBNNAdasisConfigProfilelongTrafficSignIds.h"
#import "MBNNAdasisConfigLonLat.h"
#import "MBNNAdasisConfigProfilelongTrafficSigns.h"
#import "MBNNAdasisConfigTrafficEvent.h"
#import "MBNNAdasisConfigWeather.h"
#import "MBNNAdasisConfigCustomTrafficEvents.h"
#import "MBNNAdasisConfigProfilelongTypeOptions.h"
#import "MBNNStub.h"
#import "MBNNSegment.h"
#import "MBNNProfileshort.h"
#import "MBNNProfilelong.h"
#import "MBNNAdasisConfigPathOptions.h"
#import "MBNNAdasisConfig.h"
#import "MBNNAdasisConfigBuilder.h"
