// This file is generated and will be overwritten automatically.

#import <Foundation/Foundation.h>

@class MBNNActiveGuidanceInfo;
@class MBNNBannerInstruction;
@class MBNNCorrectedLocationData;
@class MBNNFixLocation;
@class MBNNHdMatchingResult;
@class MBNNMapMatcherOutput;
@class MBNNRoadName;
@class MBNNRouteIndices;
@class MBNNSpeedLimit;
@class MBNNTurnLane;
@class MBNNUpcomingRouteAlertUpdate;
@class MBNNVoiceInstruction;
typedef NS_ENUM(NSInteger, MBNNOffRoadStateProvider);
typedef NS_ENUM(NSInteger, MBNNRouteState);

NS_SWIFT_NAME(NavigationStatus)
__attribute__((visibility ("default")))
@interface MBNNNavigationStatus : NSObject

// This class provides custom init which should be called
- (nonnull instancetype)init NS_UNAVAILABLE;

// This class provides custom init which should be called
+ (nonnull instancetype)new NS_UNAVAILABLE;


/**
 * We didn't have location updates for too much time.
 * This can be handled as "grey puck" or "No GPS" on client side.
 */
@property (nonatomic, readonly) BOOL stale;

/**
 * `true` if status was produced in "fallback" mode, i.e. navigation tiles were not used
 * (e.g. they are not available), usually it means worse user experience
 */
@property (nonatomic, readonly) BOOL isFallback;

/** is current location belongs to tunnel */
@property (nonatomic, readonly) BOOL inTunnel;

/** is current location belongs to parking aisle */
@property (nonatomic, readonly) BOOL inParkingAisle;

/** current position is in roundabout */
@property (nonatomic, readonly) BOOL inRoundabout;

/** "prediction" time, i.e. duration between this status and the latest location update */
@property (nonatomic, readonly) NSTimeInterval predicted;

/**
 * Id of alternative route that we matched. This field calculated in OffRoute `routeState`.
 *  `nullopt` for non-OffRoute `routeState` or if no one alternative route matches.
 */
@property (nonatomic, readonly, nullable, copy) NSString *locatedAlternativeRouteId;

/** voice instruction to be presented */
@property (nonatomic, readonly, nullable) MBNNVoiceInstruction *voiceInstruction;

/** banner instruction to be presented */
@property (nonatomic, readonly, nullable) MBNNBannerInstruction *bannerInstruction;

/**
 * Current speed limit
 *
 *  For more accurate speed limit, depending on time / weather / etc conditions use GraphAccessor.getAdasAttributes(EdgeId)
 */
@property (nonatomic, readonly, nonnull) MBNNSpeedLimit *speedLimit;

/** Output of map matcher on this status. */
@property (nonatomic, readonly, nonnull) MBNNMapMatcherOutput *mapMatcherOutput;

/**
 * Probability of vehicle to be off-road:
 * 1.0 - vehicle is definitely off-road, 0.0 - vehicle is definitely on-road
 */
@property (nonatomic, readonly) float offRoadProba;

/**
 * Off road state provider.
 * This field can be used to understand which off-road detector had the greatest impact on determining off-road state.
 * Used as internal nav-native field to debug off-road logic.
 */
@property (nonatomic, readonly) MBNNOffRoadStateProvider offRoadStateProvider;

/** Will be empty if we are in free-drive now (i.e. routeState == invalid) */
@property (nonatomic, readonly, nullable) MBNNActiveGuidanceInfo *activeGuidanceInfo;

/**
 * Index of the next waypoint on the route in the list of waypoints. If no waypoints - 0.
 * Added by server waypoints are also counted.
 */
@property (nonatomic, readonly) uint32_t nextWaypointIndex;

/** current Z-level, can be used to build route from proper level of road */
@property (nonatomic, readonly, nullable) NSNumber *layer;

/** True if location is generated by dead-reckoning corrector */
@property (nonatomic, readonly) BOOL isSyntheticLocation;

/** Local system time of the map matched get status */
@property (nonatomic, readonly, nonnull) NSDate *mapMatchedSystemTime;

/**
 *  Nullopt if adas cache is OFF, e.g. neither ADASIS nor EH enabled
 *  True if ADAS tiles are loaded for the current location
 *  False if ADAS cache is ON, but no tiles around
 */
@property (nonatomic, readonly, nullable) NSNumber *isAdasDataAvailable;


@end
